[#73] 메인페이지 구현
2P3S/scrum-dice pull request #74
Opened 2023-06-25 06:44 UTC by hyunnnn98

## What

[//]: # (Pull Request 에서 무엇을 작업했는지 작성)

* #73 

## Why

[//]: # (Pull Request 에서 왜 이 작업을 하게 되었는지 작성)

* 메인 페이지 컴포넌트 구현

## Change details

[//]: # (작업한 내용에 대한 자세한 설명)

* git issue 참조

## Request to reviewers

[//]: # (PR 작성자가 리뷰어에게 어떤 부분을 물어보고 싶은지 작성)

* 메인 컴포넌트의 `지금 바로 시작해보세요` 버튼을 통해 Room 생성 페이지로 이동이 되는지 확인.

2023-06-25 17:08 UTC, JeongJaeSoon requested changes

2023-06-25 17:08 UTC, JeongJaeSoon commented on src/components/templates/Main/index.tsx
> +    </main>
전체적으로 문장이 부자연스러운 느낌이 남

2023-06-25 17:08 UTC, JeongJaeSoon commented on src/components/templates/Main/index.tsx
> +    </main>
```suggestion
    <main className="m-auto max-w-md py-32 text-center">
      <Paragraph size="large" className="mb-4">
        팀의 플래닝 포커가 얼마나 더 편리하고 친밀해질 수 있는지, 그리고 우리의 Scrum Dice 서비스가 어떤 혜택을 제공하는지 알려드릴게요!
      </Paragraph>
      <Title headingLevel="h1" className="font-notoSansKr !text-4xl font-bold text-blue-600 mb-10">
        어서오세요! 팀원들과 함께 하는 플래닝 포커가 더욱 편리하고 친밀한 경험으로 다가옵니다. 우리의 Scrum Dice가 여러분의 팀워크를 한층 더 강화시켜드릴 거예요.
      </Title>
      <Paragraph size="small" className="px-5 mb-10 text-slate-500">
        우선, 시간을 아껴드리는 기능이 준비되어 있습니다. 회차별 평균을 자동으로 계산해줘서 회의 시간을 획기적으로 단축시켜줄 거예요. 그러면 논의 시간을 줄이고 빠르게 팀 결정을 내릴 수 있답니다.

또한, 스트레스를 날려줄 준비가 되어있어요! 애그 타이머와 쉬어가기 기능을 통해 플래닝 포커에 대한 스트레스를 최소화하고, 집중력을 높일 수 있답니다. 팀원 모두가 편안하고 즐거운 분위기에서 참여할 수 있을 거예요.

기록 저장과 조회는 물론 가능합니다! 모든 회차의 플래닝 포커 결과가 자동으로 저장되어 편리하게 참고할 수 있답니다. 게다가, 매 회차마다 이름을 원하는 대로 커스터마이즈하여 구분할 수 있어 팀의 작업 환경을 개인화할 수 있답니다.

지금까지 불편했던 점들을 해결하고, 더욱 친밀하고 효율적인 플래닝 포커 경험을 위해 Scrum Dice를 함께 해보세요. 팀의 결속력을 강화하고, 일정을 원활히 진행할 수 있을 거예요.
      </Paragraph>
      <LinkButton href="/room" className="rounded-full px-12">
        Scrum Dice와 함께라면, 플래닝 포커는 더욱 편리하고 친밀한 시간으로 변화될 거예요. 지금 바로 시작해보세요!
      </LinkButton>
    </main>
```

2023-06-25 17:08 UTC, JeongJaeSoon commented on src/components/templates/Main/index.tsx
> +    </main>
```suggestion
    <main className="m-auto max-w-md py-32 text-center">
      <Paragraph size="large" className="mb-4">
        더욱 효율적인 플래닝 포커를 위한 Scrum Dice
      </Paragraph>
      <Title headingLevel="h1" className="font-notoSansKr !text-4xl font-bold text-blue-600 mb-10">
        팀의 플래닝 포커를 편리하고 친밀하게 만들어줄 Scrum Dice(또는 Scrum-dice)를 소개합니다!
      </Title>
      <Paragraph size="small" className="px-5 mb-10 text-slate-500">
        * 시간 절약: 회차별 평균을 자동으로 계산하여 빠른 결정을 도와줍니다.
        * 스트레스 해소: 애그 타이머와 쉬어가기 기능으로 플래닝 포커에 대한 스트레스를 낮추고 집중력을 높일 수 있습니다.
        * 기록 저장 및 조회: 모든 회차의 결과를 자동으로 저장하고 커스텀한 이름으로 구분하여 쉽게 조회할 수 있습니다.
      </Paragraph>
      <LinkButton href="/room" className="rounded-full px-12">
        Scrum Dice와 함께라면, 플래닝 포커를 더욱 효율적이고 친밀하게 진행할 수 있습니다. 지금 바로 시작해보세요!
      </LinkButton>
    </main>
```

2023-06-26 11:47 UTC, JeongJaeSoon commented on src/components/templates/Main/index.tsx
> +    </main>
하단의 상세 설명 부분 삭제하기로 함

2023-08-06 14:15 UTC, hyunnnn98 commented on src/components/templates/Main/index.tsx
> +    </main>
https://github.com/2P3S/2p3s-scrum-dice/pull/74/commits/0a191c6a5a7cf25f889ad357361abcd2c5ca96a8
수정 완료

2023-08-27 11:06 UTC, Samsam-lee submitted a review, later dismissed
LGTM 👍🏻

2023-08-27 11:08 UTC, JeongJaeSoon requested changes
확인 바랍니당

2023-08-27 11:08 UTC, JeongJaeSoon commented on src/components/templates/Main/index.tsx
> +      </Paragraph> */}
주석 미삭제

2023-08-27 11:08 UTC, JeongJaeSoon commented on src/pages/index.tsx
> +        <meta name="description" content="지금까지 없던 혁신적인 플래닝 포커 Scrum Dice" />
기존에 있던 문구를 좀 정리해서 description 에 100~120자 내외로 넣으면 좋을듯

2023-08-27 11:28 UTC, hyunnnn98 commented on src/components/templates/Main/index.tsx
> +      </Paragraph> */}
삭제완료

2023-08-27 11:28 UTC, hyunnnn98 commented on src/pages/index.tsx
> +        <meta name="description" content="지금까지 없던 혁신적인 플래닝 포커 Scrum Dice" />
Scrum Dice로 효율적인 플래닝 포커를 진행하세요! 다양한 기능을 제공하여 팀의 빠른 의사 결정을 도와드립니다. 지금 바로 시작해보세요!

문구로 결정.

2023-08-27 11:37 UTC, hyunnnn98 commented on src/pages/index.tsx
> +        <meta name="description" content="지금까지 없던 혁신적인 플래닝 포커 Scrum Dice" />
<img width="1111" alt="image" src="https://github.com/2P3S/2p3s-scrum-dice/assets/52916934/4d972b01-a1fd-4bdd-96c8-27b4f8e833dd">
페이지 소스 확인

2023-08-27 11:38 UTC, JeongJaeSoon approved these changes
LGTM

2023-08-27 11:39 UTC, merged